spring:
  profiles:
    active:
    - common
  application:
    name: ${project.server-one.name}
  boot:
    admin:
      client:
        url: http://127.0.0.1:8180
eureka:
  client:
    service-url:
      defaultZone: ${project.register.one.service-url}