spring:
  application:
    name: server-one
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
logging:
  level:
    root: info
management:
  security:
    enabled: false