logging:
  level:
    root: info
project:
  register:
    name: cloud-register
    one:
      hostname: 127.0.0.1
      port: 8100
      service-url: http://${project.register.one.hostname}:${project.register.one.port}/eureka/
    two:
      hostname: 127.0.0.1
      port: 8101
      service-url: http://${project.register.two.hostname}:${project.register.two.port}/eureka/
    three:
      hostname: 127.0.0.1
      port: 8102
      service-url: http://${project.register.three.hostname}:${project.register.three.port}/eureka/
      
      
  admin:
    name: service-admin
    port: 8180
    
  server-one:
    name: server-one
    port:
      one: 8111
    