spring:
  profiles:
    active:
    - common
  application:
    name: ${project.register.name}
server:
  port: ${project.register.one.port}
eureka:
  instance:
    hostname: ${project.register.one.hostname}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${project.register.one.service-url}