spring:
  profiles:
    active:
    - common
  application:
    name: ${project.admin.name}
server:
  port: ${project.admin.port}
eureka:
  client:
    service-url:
      defaultZone: ${project.register.one.service-url}
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always