spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangLijia0901/spring-cloud.git
          search-paths: config-server/config-repo
          username: ZhangLijia0901
          password: zhang1997
          default-label: master
server:
  port: 8140
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
logging:
  level:
    root: debug