logging:
  level:
    root: info
    com.lj: debug
## --
server:
  port: 8080
wx: 
  appid: wx86355b69b0af0b7c
  appsecret: 39af27b8e647b599823a3089317f81b4
  token: HafS3ZIotbjisg1YBfRKM2xQYGg6sRXD
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.3.245:1521:orcl
    username: CRC_SCOTT
    password: CRC_SCOTT
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.lj.webflux.entity
swagger:
  enabled: true
  ## 维护人 
  contact:    name: 
    email: 
    url: 
  description: 描述
  base-package: 
  
